//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KeyCabinetKiosk {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Language_EN {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Language_EN() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("KeyCabinetKiosk.Language_EN", typeof(Language_EN).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access.
        /// </summary>
        internal static string ACCESS {
            get {
                return ResourceManager.GetString("ACCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access and Card.
        /// </summary>
        internal static string ACCESS_AND_CARD {
            get {
                return ResourceManager.GetString("ACCESS_AND_CARD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access Code.
        /// </summary>
        internal static string ACCESS_CODE {
            get {
                return ResourceManager.GetString("ACCESS_CODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no user
        ///assigned to this
        ///access code..
        /// </summary>
        internal static string ACCESS_CODE_NO_USER {
            get {
                return ResourceManager.GetString("ACCESS_CODE_NO_USER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access Code Not Found.
        /// </summary>
        internal static string ACCESS_CODE_NOT_FOUND {
            get {
                return ResourceManager.GetString("ACCESS_CODE_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access Code Only.
        /// </summary>
        internal static string ACCESS_CODE_ONLY {
            get {
                return ResourceManager.GetString("ACCESS_CODE_ONLY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access Method.
        /// </summary>
        internal static string ACCESS_METHOD {
            get {
                return ResourceManager.GetString("ACCESS_METHOD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access Restriction Type.
        /// </summary>
        internal static string ACCESS_RESTRICTION_TYPE {
            get {
                return ResourceManager.GetString("ACCESS_RESTRICTION_TYPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access Restrictions.
        /// </summary>
        internal static string ACCESS_RESTRICTIONS {
            get {
                return ResourceManager.GetString("ACCESS_RESTRICTIONS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Another
        ///User.
        /// </summary>
        internal static string ADD_ANOTHER_USER {
            get {
                return ResourceManager.GetString("ADD_ANOTHER_USER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add User.
        /// </summary>
        internal static string ADD_USER {
            get {
                return ResourceManager.GetString("ADD_USER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Admin Email.
        /// </summary>
        internal static string ADMIN_EMAIL_ADDRESS {
            get {
                return ResourceManager.GetString("ADMIN_EMAIL_ADDRESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Admin Password.
        /// </summary>
        internal static string ADMIN_PASSWORD {
            get {
                return ResourceManager.GetString("ADMIN_PASSWORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service Manager Number.
        /// </summary>
        internal static string ADMIN_PHONE_NUMBER {
            get {
                return ResourceManager.GetString("ADMIN_PHONE_NUMBER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Administrative Tasks.
        /// </summary>
        internal static string ADMIN_TASKS {
            get {
                return ResourceManager.GetString("ADMIN_TASKS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Admin TextMsg Number.
        /// </summary>
        internal static string ADMIN_TEXT_NUMBER {
            get {
                return ResourceManager.GetString("ADMIN_TEXT_NUMBER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Scan The
        ///Same Finger Again
        ///For Enrollment
        ///Scan Count = .
        /// </summary>
        internal static string AGAIN_SCAN_FINGERPRINT {
            get {
                return ResourceManager.GetString("AGAIN_SCAN_FINGERPRINT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Always On.
        /// </summary>
        internal static string ALWAYS_ON {
            get {
                return ResourceManager.GetString("ALWAYS_ON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply Changes.
        /// </summary>
        internal static string APPLY_CHANGES {
            get {
                return ResourceManager.GetString("APPLY_CHANGES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Would You Like To.
        /// </summary>
        internal static string ASK_TEXT_MESSAGE_1 {
            get {
                return ResourceManager.GetString("ASK_TEXT_MESSAGE_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Receive A Text Receipt?.
        /// </summary>
        internal static string ASK_TEXT_MESSAGE_2 {
            get {
                return ResourceManager.GetString("ASK_TEXT_MESSAGE_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BkSp.
        /// </summary>
        internal static string BACKSPACE {
            get {
                return ResourceManager.GetString("BACKSPACE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Barcode Scanning Error:
        ///No Barcode Data Scanned.
        /// </summary>
        internal static string BARCODE_SCANNING_ERROR {
            get {
                return ResourceManager.GetString("BARCODE_SCANNING_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bike.
        /// </summary>
        internal static string BIKE {
            get {
                return ResourceManager.GetString("BIKE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Choose A Type
        ///Of Bike.
        /// </summary>
        internal static string BIKE_CHOOSE {
            get {
                return ResourceManager.GetString("BIKE_CHOOSE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Biometric Enrollment.
        /// </summary>
        internal static string BIOMETRIC_ENROLLMENT {
            get {
                return ResourceManager.GetString("BIOMETRIC_ENROLLMENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set Box Access.
        /// </summary>
        internal static string BOX_ACCESS {
            get {
                return ResourceManager.GetString("BOX_ACCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Box Info.
        /// </summary>
        internal static string BOX_INFO {
            get {
                return ResourceManager.GetString("BOX_INFO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Box location not set.
        /// </summary>
        internal static string BOX_LOCATION_NOT_SET {
            get {
                return ResourceManager.GetString("BOX_LOCATION_NOT_SET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Box Number.
        /// </summary>
        internal static string BOX_NUMBER {
            get {
                return ResourceManager.GetString("BOX_NUMBER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Box number does
        ///not exist.
        /// </summary>
        internal static string BOX_NUMBER_NOT_EXIST {
            get {
                return ResourceManager.GetString("BOX_NUMBER_NOT_EXIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Press Screen To Start.
        /// </summary>
        internal static string BUTTON_START {
            get {
                return ResourceManager.GetString("BUTTON_START", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cabinet Box Access.
        /// </summary>
        internal static string CABINET_BOX_ACCESS {
            get {
                return ResourceManager.GetString("CABINET_BOX_ACCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cabinet Door Transactions.
        /// </summary>
        internal static string CABINET_DOOR_TRANSACTIONS {
            get {
                return ResourceManager.GetString("CABINET_DOOR_TRANSACTIONS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string CANCEL {
            get {
                return ResourceManager.GetString("CANCEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancelled.
        /// </summary>
        internal static string CANCELLED {
            get {
                return ResourceManager.GetString("CANCELLED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Caps.
        /// </summary>
        internal static string CAPITALS_LOCK {
            get {
                return ResourceManager.GetString("CAPITALS_LOCK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Card Number.
        /// </summary>
        internal static string CARD_NUMBER {
            get {
                return ResourceManager.GetString("CARD_NUMBER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Swipe Cancelled
        ///Try Again.
        /// </summary>
        internal static string CARD_READ_CANCELLED {
            get {
                return ResourceManager.GetString("CARD_READ_CANCELLED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Card not read
        ///Try Again.
        /// </summary>
        internal static string CARD_READ_FAILED {
            get {
                return ResourceManager.GetString("CARD_READ_FAILED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timed out
        ///Try Again.
        /// </summary>
        internal static string CARD_READ_TIMEOUT {
            get {
                return ResourceManager.GetString("CARD_READ_TIMEOUT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scan error:
        ///Try again.
        /// </summary>
        internal static string CARD_SWIPE_ERROR {
            get {
                return ResourceManager.GetString("CARD_SWIPE_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Admin Password.
        /// </summary>
        internal static string CHANGE_ADMIN_PWORD {
            get {
                return ResourceManager.GetString("CHANGE_ADMIN_PWORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change
        ///Password.
        /// </summary>
        internal static string CHANGE_PASSWORD {
            get {
                return ResourceManager.GetString("CHANGE_PASSWORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose .csv or .xml File for Importing.
        /// </summary>
        internal static string CHOOSE_IMPORT_FILE {
            get {
                return ResourceManager.GetString("CHOOSE_IMPORT_FILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear Enrolled Fingerprints.
        /// </summary>
        internal static string CLEAR_ENROLLED_FINGERPRINTS {
            get {
                return ResourceManager.GetString("CLEAR_ENROLLED_FINGERPRINTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fingerprints Found
        ///With Another ID.
        ///Clear Old Prints?.
        /// </summary>
        internal static string CLEAR_FINGERPRINT_QUESTION {
            get {
                return ResourceManager.GetString("CLEAR_FINGERPRINT_QUESTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear Scan Table.
        /// </summary>
        internal static string CLEAR_SCAN_TABLE {
            get {
                return ResourceManager.GetString("CLEAR_SCAN_TABLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Communicating with
        ///Server....
        /// </summary>
        internal static string COMMUNICATING_WITH_SERVER {
            get {
                return ResourceManager.GetString("COMMUNICATING_WITH_SERVER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unrecoverable Error running application.
        /// </summary>
        internal static string CONFIGURATION_APP_ERROR {
            get {
                return ResourceManager.GetString("CONFIGURATION_APP_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unrecoverable Error in configuration file.
        /// </summary>
        internal static string CONFIGURATION_FILE_ERROR {
            get {
                return ResourceManager.GetString("CONFIGURATION_FILE_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unrecoverable Error in  opening ports.
        /// </summary>
        internal static string CONFIGURATION_OPEN_PORT_ERROR {
            get {
                return ResourceManager.GetString("CONFIGURATION_OPEN_PORT_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RFID Error in configuration file.
        /// </summary>
        internal static string CONFIGURATION_RFID_ERROR_1 {
            get {
                return ResourceManager.GetString("CONFIGURATION_RFID_ERROR_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WARNING:If you do not exit, additional program errors may occur.
        ///Do you want to Continue?.
        /// </summary>
        internal static string CONFIGURATION_RFID_ERROR_2 {
            get {
                return ResourceManager.GetString("CONFIGURATION_RFID_ERROR_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm.
        /// </summary>
        internal static string CONFIRM {
            get {
                return ResourceManager.GetString("CONFIRM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///
        ///Is License Number Correct?
        ///.
        /// </summary>
        internal static string CONFIRM_LICENSE {
            get {
                return ResourceManager.GetString("CONFIRM_LICENSE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///Is This Name Correct?
        ///.
        /// </summary>
        internal static string CONFIRM_NAME {
            get {
                return ResourceManager.GetString("CONFIRM_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continue.
        /// </summary>
        internal static string CONTINUE {
            get {
                return ResourceManager.GetString("CONTINUE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Credit Card Only.
        /// </summary>
        internal static string CREDIT_CARD_ONLY {
            get {
                return ResourceManager.GetString("CREDIT_CARD_ONLY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Access: .
        /// </summary>
        internal static string CURRENT_ACCESS {
            get {
                return ResourceManager.GetString("CURRENT_ACCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data File Contains Errors
        ///Or Does Not Exist..
        /// </summary>
        internal static string DATA_FILE_ERRORS_NOT_EXIST {
            get {
                return ResourceManager.GetString("DATA_FILE_ERRORS_NOT_EXIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data File Contains Errors..
        /// </summary>
        internal static string DATA_FILE_HAS_ERRORS {
            get {
                return ResourceManager.GetString("DATA_FILE_HAS_ERRORS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data File Does Not Exist..
        /// </summary>
        internal static string DATA_FILE_NOT_EXIST {
            get {
                return ResourceManager.GetString("DATA_FILE_NOT_EXIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Must Be.
        /// </summary>
        internal static string DATA_LENGTH_ERROR {
            get {
                return ResourceManager.GetString("DATA_LENGTH_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///Characters Long.
        /// </summary>
        internal static string DATA_LENGTH_ERROR_2 {
            get {
                return ResourceManager.GetString("DATA_LENGTH_ERROR_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Update Thread Error.
        /// </summary>
        internal static string DATA_UPDATE_ERROR {
            get {
                return ResourceManager.GetString("DATA_UPDATE_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data View Set 
        ///Thread Error.
        /// </summary>
        internal static string DATA_VIEW_THREAD_ERROR {
            get {
                return ResourceManager.GetString("DATA_VIEW_THREAD_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database Error.
        ///Try Again or Please Call
        ///.
        /// </summary>
        internal static string DATABASE_ERROR {
            get {
                return ResourceManager.GetString("DATABASE_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete User.
        /// </summary>
        internal static string DELETE_USER {
            get {
                return ResourceManager.GetString("DELETE_USER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Department.
        /// </summary>
        internal static string DEPARTMENT {
            get {
                return ResourceManager.GetString("DEPARTMENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This box&apos;s timeframe
        ///has not arrived yet.
        ///Door opening cancelled..
        /// </summary>
        internal static string DOOR_TIMEFRAME_BOX_ERROR {
            get {
                return ResourceManager.GetString("DOOR_TIMEFRAME_BOX_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This box&apos;s timeframe
        ///has already passed.
        ///Door opening cancelled..
        /// </summary>
        internal static string DOOR_TIMEFRAME_BOX_ERROR_2 {
            get {
                return ResourceManager.GetString("DOOR_TIMEFRAME_BOX_ERROR_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This user&apos;s timeframe
        ///has not arrived yet.
        ///Door opening cancelled..
        /// </summary>
        internal static string DOOR_TIMEFRAME_USER_ERROR {
            get {
                return ResourceManager.GetString("DOOR_TIMEFRAME_USER_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This user&apos;s timeframe
        ///has already passed.
        ///Door opening cancelled..
        /// </summary>
        internal static string DOOR_TIMEFRAME_USER_ERROR_2 {
            get {
                return ResourceManager.GetString("DOOR_TIMEFRAME_USER_ERROR_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This box has no more
        ///usages available.
        ///Door opening cancelled..
        /// </summary>
        internal static string DOOR_USAGES_BOX_ERROR {
            get {
                return ResourceManager.GetString("DOOR_USAGES_BOX_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This user has no more
        ///usages available.
        ///Door opening cancelled..
        /// </summary>
        internal static string DOOR_USAGES_USER_ERROR {
            get {
                return ResourceManager.GetString("DOOR_USAGES_USER_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Driver&apos;s First Name.
        /// </summary>
        internal static string DRIVER_FIRST_NAME {
            get {
                return ResourceManager.GetString("DRIVER_FIRST_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Driver&apos;s Last Name.
        /// </summary>
        internal static string DRIVER_LAST_NAME {
            get {
                return ResourceManager.GetString("DRIVER_LAST_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Driver&apos;s License Number.
        /// </summary>
        internal static string DRIVER_NUMBER {
            get {
                return ResourceManager.GetString("DRIVER_NUMBER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EBike.
        /// </summary>
        internal static string EBIKE {
            get {
                return ResourceManager.GetString("EBIKE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        internal static string EMAIL {
            get {
                return ResourceManager.GetString("EMAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email Address.
        /// </summary>
        internal static string EMAIL_ADDRESS {
            get {
                return ResourceManager.GetString("EMAIL_ADDRESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email Address Not
        ///Formatted Properly.
        /// </summary>
        internal static string EMAIL_ADDRESS_NOT_FORMATTED {
            get {
                return ResourceManager.GetString("EMAIL_ADDRESS_NOT_FORMATTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email Failed.
        ///Local Copy Stored.
        ///Contact Admin.
        ///Thank You.
        /// </summary>
        internal static string EMAIL_FAILED {
            get {
                return ResourceManager.GetString("EMAIL_FAILED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email Successful
        ///
        ///Thank You..
        /// </summary>
        internal static string EMAIL_SUCCESSFUL {
            get {
                return ResourceManager.GetString("EMAIL_SUCCESSFUL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email Transaction Report.
        /// </summary>
        internal static string EMAIL_TRANSACTION_REPORT {
            get {
                return ResourceManager.GetString("EMAIL_TRANSACTION_REPORT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transaction History
        ///Failed
        ///Contact Admin.
        ///Thank You.
        /// </summary>
        internal static string EMAIL_TRANSACTIONS_FAILED {
            get {
                return ResourceManager.GetString("EMAIL_TRANSACTIONS_FAILED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transaction History
        ///Successful
        ///Thank You.
        /// </summary>
        internal static string EMAIL_TRANSACTIONS_SUCCESSFUL {
            get {
                return ResourceManager.GetString("EMAIL_TRANSACTIONS_SUCCESSFUL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ending Door Number.
        /// </summary>
        internal static string END_DOOR_NUMBER {
            get {
                return ResourceManager.GetString("END_DOOR_NUMBER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End Time.
        /// </summary>
        internal static string END_TIME {
            get {
                return ResourceManager.GetString("END_TIME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enroll New Fingerprint.
        /// </summary>
        internal static string ENROLL_FINGERPRINTS {
            get {
                return ResourceManager.GetString("ENROLL_FINGERPRINTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of Enrolled
        ///Fingerprints For
        ///User ID: .
        /// </summary>
        internal static string ENROLLED_FINGERPRINT_COUNT {
            get {
                return ResourceManager.GetString("ENROLLED_FINGERPRINT_COUNT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter.
        /// </summary>
        internal static string ENTER {
            get {
                return ResourceManager.GetString("ENTER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter
        ///Access
        ///Code.
        /// </summary>
        internal static string ENTER_ACCESS_CODE {
            get {
                return ResourceManager.GetString("ENTER_ACCESS_CODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter
        ///Box
        ///Number.
        /// </summary>
        internal static string ENTER_BOX_NUMBER {
            get {
                return ResourceManager.GetString("ENTER_BOX_NUMBER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter
        ///Card
        ///Number.
        /// </summary>
        internal static string ENTER_CARD_NUMBER {
            get {
                return ResourceManager.GetString("ENTER_CARD_NUMBER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter
        ///Code To
        ///Change.
        /// </summary>
        internal static string ENTER_CODE {
            get {
                return ResourceManager.GetString("ENTER_CODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Department Name.
        /// </summary>
        internal static string ENTER_DEPARTMENT_NAME {
            get {
                return ResourceManager.GetString("ENTER_DEPARTMENT_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter
        ///Door
        ///Delay.
        /// </summary>
        internal static string ENTER_DOOR_DELAY {
            get {
                return ResourceManager.GetString("ENTER_DOOR_DELAY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Email Address.
        /// </summary>
        internal static string ENTER_EMAIL_ADDRESS {
            get {
                return ResourceManager.GetString("ENTER_EMAIL_ADDRESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter
        ///End
        ///Door.
        /// </summary>
        internal static string ENTER_END_DOOR {
            get {
                return ResourceManager.GetString("ENTER_END_DOOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter
        ///End
        ///Time.
        /// </summary>
        internal static string ENTER_END_TIME {
            get {
                return ResourceManager.GetString("ENTER_END_TIME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter First Name.
        /// </summary>
        internal static string ENTER_FIRST_NAME {
            get {
                return ResourceManager.GetString("ENTER_FIRST_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Group Name.
        /// </summary>
        internal static string ENTER_GROUP_NAME {
            get {
                return ResourceManager.GetString("ENTER_GROUP_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter ID.
        /// </summary>
        internal static string ENTER_ID {
            get {
                return ResourceManager.GetString("ENTER_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Last Name.
        /// </summary>
        internal static string ENTER_LAST_NAME {
            get {
                return ResourceManager.GetString("ENTER_LAST_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Driver&apos;s License Number.
        /// </summary>
        internal static string ENTER_LICENSE_NUMBER {
            get {
                return ResourceManager.GetString("ENTER_LICENSE_NUMBER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter
        ///Limited
        /// Uses.
        /// </summary>
        internal static string ENTER_LIMITED_USES {
            get {
                return ResourceManager.GetString("ENTER_LIMITED_USES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter
        ///New
        ///Code.
        /// </summary>
        internal static string ENTER_NEW_CODE {
            get {
                return ResourceManager.GetString("ENTER_NEW_CODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter New ID.
        /// </summary>
        internal static string ENTER_NEW_ID {
            get {
                return ResourceManager.GetString("ENTER_NEW_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Car
        ///Odometer
        ///Reading.
        /// </summary>
        internal static string ENTER_ODOMETER_READING {
            get {
                return ResourceManager.GetString("ENTER_ODOMETER_READING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter
        ///Operator
        ///Number.
        /// </summary>
        internal static string ENTER_OPERATOR_NUMBER {
            get {
                return ResourceManager.GetString("ENTER_OPERATOR_NUMBER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter
        ///Phone
        ///Number.
        /// </summary>
        internal static string ENTER_PHONE_NUMBER {
            get {
                return ResourceManager.GetString("ENTER_PHONE_NUMBER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter RFID Tag Number.
        /// </summary>
        internal static string ENTER_RFID_TAG {
            get {
                return ResourceManager.GetString("ENTER_RFID_TAG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter
        ///Start
        ///Door.
        /// </summary>
        internal static string ENTER_START_DOOR {
            get {
                return ResourceManager.GetString("ENTER_START_DOOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter
        ///Start
        ///Time.
        /// </summary>
        internal static string ENTER_START_TIME {
            get {
                return ResourceManager.GetString("ENTER_START_TIME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter User ID.
        /// </summary>
        internal static string ENTER_USER_ID {
            get {
                return ResourceManager.GetString("ENTER_USER_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter User ID to be Deleted.
        /// </summary>
        internal static string ENTER_USER_ID_DELETE {
            get {
                return ResourceManager.GetString("ENTER_USER_ID_DELETE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter ID of User to be Modified.
        /// </summary>
        internal static string ENTER_USER_ID_MODIFY {
            get {
                return ResourceManager.GetString("ENTER_USER_ID_MODIFY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter
        ///Vehicle
        ///Number.
        /// </summary>
        internal static string ENTER_VEHICLE_NUMBER {
            get {
                return ResourceManager.GetString("ENTER_VEHICLE_NUMBER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        internal static string EXIT {
            get {
                return ResourceManager.GetString("EXIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Each vehicle contains a
        ///yellow folder with vehicle
        ///assigned mileage logs.
        ///Drivers are required to fill
        ///the log out completely
        ///for each driving day.
        /// </summary>
        internal static string FILL_OUT_MILEAGE_FORM {
            get {
                return ResourceManager.GetString("FILL_OUT_MILEAGE_FORM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fingerprint Match
        ///Failed.
        /// </summary>
        internal static string FINGERPRINT_FAILED {
            get {
                return ResourceManager.GetString("FINGERPRINT_FAILED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fingerprint Match
        ///Successful.
        /// </summary>
        internal static string FINGERPRINT_MATCHED {
            get {
                return ResourceManager.GetString("FINGERPRINT_MATCHED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fingerprints Cleared.
        /// </summary>
        internal static string FINGERPRINTS_CLEARED {
            get {
                return ResourceManager.GetString("FINGERPRINTS_CLEARED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Name.
        /// </summary>
        internal static string FIRST_NAME {
            get {
                return ResourceManager.GetString("FIRST_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group.
        /// </summary>
        internal static string GROUP {
            get {
                return ResourceManager.GetString("GROUP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter
        ///Code.
        /// </summary>
        internal static string HIDDEN_EXIT_KEYPAD_MESSAGE {
            get {
                return ResourceManager.GetString("HIDDEN_EXIT_KEYPAD_MESSAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter User ID For Biometric Enrolling.
        /// </summary>
        internal static string ID_BIOMETRIC_ENROLLING {
            get {
                return ResourceManager.GetString("ID_BIOMETRIC_ENROLLING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID Number not unique.
        /// </summary>
        internal static string ID_NUM_NOT_UNIQUE {
            get {
                return ResourceManager.GetString("ID_NUM_NOT_UNIQUE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID #.
        /// </summary>
        internal static string ID_NUMBER {
            get {
                return ResourceManager.GetString("ID_NUMBER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID Scan Confirmed
        ///Please Remove License.
        /// </summary>
        internal static string ID_SCAN_CONFIRMED {
            get {
                return ResourceManager.GetString("ID_SCAN_CONFIRMED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID Scan Timed Out.
        /// </summary>
        internal static string ID_SCAN_TIMED_OUT {
            get {
                return ResourceManager.GetString("ID_SCAN_TIMED_OUT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID Scanner Error.
        /// </summary>
        internal static string ID_SCANNER_ERROR {
            get {
                return ResourceManager.GetString("ID_SCANNER_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import Complete
        ///Remove USB Drive..
        /// </summary>
        internal static string IMPORT_COMPLETE {
            get {
                return ResourceManager.GetString("IMPORT_COMPLETE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Importing Access Code
        ///data or User data?.
        /// </summary>
        internal static string IMPORT_QUESTION {
            get {
                return ResourceManager.GetString("IMPORT_QUESTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Importing....
        /// </summary>
        internal static string IMPORTING {
            get {
                return ResourceManager.GetString("IMPORTING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information.
        /// </summary>
        internal static string INFORMATION {
            get {
                return ResourceManager.GetString("INFORMATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert USB Drive.
        /// </summary>
        internal static string INSERT_USB_DRIVE {
            get {
                return ResourceManager.GetString("INSERT_USB_DRIVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid access type.
        /// </summary>
        internal static string INVALID_ACCESS_TYPE {
            get {
                return ResourceManager.GetString("INVALID_ACCESS_TYPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid box number
        ///Try Again.
        /// </summary>
        internal static string INVALID_BOX_NUMBER {
            get {
                return ResourceManager.GetString("INVALID_BOX_NUMBER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Location
        ///Try Again.
        /// </summary>
        internal static string INVALID_LOCATION {
            get {
                return ResourceManager.GetString("INVALID_LOCATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Password.
        /// </summary>
        internal static string INVALID_PASSWORD {
            get {
                return ResourceManager.GetString("INVALID_PASSWORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Time.
        /// </summary>
        internal static string INVALID_TIME {
            get {
                return ResourceManager.GetString("INVALID_TIME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Name.
        /// </summary>
        internal static string LAST_NAME {
            get {
                return ResourceManager.GetString("LAST_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Limit + Time Period.
        /// </summary>
        internal static string LIMIT_PLUS_TIME_PERIOD {
            get {
                return ResourceManager.GetString("LIMIT_PLUS_TIME_PERIOD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Limited Number of Uses.
        /// </summary>
        internal static string LIMITED_NUMBER_OF_USES {
            get {
                return ResourceManager.GetString("LIMITED_NUMBER_OF_USES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Limited Num. of Uses.
        /// </summary>
        internal static string LIMITED_USES {
            get {
                return ResourceManager.GetString("LIMITED_USES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manual Entry.
        /// </summary>
        internal static string MANUAL_ENTRY {
            get {
                return ResourceManager.GetString("MANUAL_ENTRY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manual ID Entry Cancelled.
        /// </summary>
        internal static string MANUAL_ID_CANCELLED {
            get {
                return ResourceManager.GetString("MANUAL_ID_CANCELLED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modify User.
        /// </summary>
        internal static string MODIFY_USER {
            get {
                return ResourceManager.GetString("MODIFY_USER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multiple Users Match
        ///Fingerprint. Try Again.
        /// </summary>
        internal static string MULTIPLE_FINGERPRINT_MATCHES {
            get {
                return ResourceManager.GetString("MULTIPLE_FINGERPRINT_MATCHES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string NAME {
            get {
                return ResourceManager.GetString("NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter New Admin Email.
        /// </summary>
        internal static string NEW_ADMIN_EMAIL {
            get {
                return ResourceManager.GetString("NEW_ADMIN_EMAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Admin Text Message Number.
        /// </summary>
        internal static string NEW_ADMIN_TXT_NUMBER {
            get {
                return ResourceManager.GetString("NEW_ADMIN_TXT_NUMBER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New number cancelled.
        /// </summary>
        internal static string NEW_NUMBER_CANCELLED {
            get {
                return ResourceManager.GetString("NEW_NUMBER_CANCELLED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Password Cancelled.
        /// </summary>
        internal static string NEW_PASSWORD_CANCELLED {
            get {
                return ResourceManager.GetString("NEW_PASSWORD_CANCELLED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Scan A New
        ///Finger For Enrollment.
        /// </summary>
        internal static string NEW_SCAN_FINGERPRINT {
            get {
                return ResourceManager.GetString("NEW_SCAN_FINGERPRINT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Empty Data Not Accepted.
        /// </summary>
        internal static string NO_EMPTY_DATA {
            get {
                return ResourceManager.GetString("NO_EMPTY_DATA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to N/A.
        /// </summary>
        internal static string NOT_AVAILABLE {
            get {
                return ResourceManager.GetString("NOT_AVAILABLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Off.
        /// </summary>
        internal static string OFF {
            get {
                return ResourceManager.GetString("OFF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string OK {
            get {
                return ResourceManager.GetString("OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Old Prints Cleared.
        /// </summary>
        internal static string OLD_PRINTS_CLEARED {
            get {
                return ResourceManager.GetString("OLD_PRINTS_CLEARED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On.
        /// </summary>
        internal static string ON {
            get {
                return ResourceManager.GetString("ON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open All Doors.
        /// </summary>
        internal static string OPEN_ALL_DOORS {
            get {
                return ResourceManager.GetString("OPEN_ALL_DOORS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Box Door.
        /// </summary>
        internal static string OPEN_BOX_DOOR {
            get {
                return ResourceManager.GetString("OPEN_BOX_DOOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Door.
        /// </summary>
        internal static string OPEN_DOOR {
            get {
                return ResourceManager.GetString("OPEN_DOOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Door Delay.
        /// </summary>
        internal static string OPEN_DOOR_DELAY {
            get {
                return ResourceManager.GetString("OPEN_DOOR_DELAY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Doors.
        /// </summary>
        internal static string OPEN_DOORS {
            get {
                return ResourceManager.GetString("OPEN_DOORS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error opening and closing relay - location: .
        /// </summary>
        internal static string OPEN_RELAY_ERROR {
            get {
                return ResourceManager.GetString("OPEN_RELAY_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opening Box.
        /// </summary>
        internal static string OPENING_BOX {
            get {
                return ResourceManager.GetString("OPENING_BOX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operation Timed Out.
        /// </summary>
        internal static string OPERATION_TIMED_OUT {
            get {
                return ResourceManager.GetString("OPERATION_TIMED_OUT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other Data.
        /// </summary>
        internal static string OTHER_DATA {
            get {
                return ResourceManager.GetString("OTHER_DATA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EBikes Are Out Of
        ///Stock. Would You Like To
        ///Rent An Normal Bike?.
        /// </summary>
        internal static string OUT_OF_STOCK_EBIKE {
            get {
                return ResourceManager.GetString("OUT_OF_STOCK_EBIKE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Normal Bikes Are Out Of
        ///Stock. Would You Like To
        ///Rent An EBike?.
        /// </summary>
        internal static string OUT_OF_STOCK_NORMAL_BIKE {
            get {
                return ResourceManager.GetString("OUT_OF_STOCK_NORMAL_BIKE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page Down.
        /// </summary>
        internal static string PAGE_DOWN {
            get {
                return ResourceManager.GetString("PAGE_DOWN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page Up.
        /// </summary>
        internal static string PAGE_UP {
            get {
                return ResourceManager.GetString("PAGE_UP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passwords must be
        ///.
        /// </summary>
        internal static string PASSWORD_LENGTH_ERROR {
            get {
                return ResourceManager.GetString("PASSWORD_LENGTH_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///characters.
        /// </summary>
        internal static string PASSWORD_LENGTH_ERROR_2 {
            get {
                return ResourceManager.GetString("PASSWORD_LENGTH_ERROR_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone.
        /// </summary>
        internal static string PHONE {
            get {
                return ResourceManager.GetString("PHONE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone Number.
        /// </summary>
        internal static string PHONE_NUMBER {
            get {
                return ResourceManager.GetString("PHONE_NUMBER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Place Enrolled
        ///Finger On
        ///Biometric Scanner.
        /// </summary>
        internal static string PLACE_ENROLLED_FINGER {
            get {
                return ResourceManager.GetString("PLACE_ENROLLED_FINGER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preparing RFID
        ///Scanner Please Wait....
        /// </summary>
        internal static string PREPARING_RFID_SCANNER_WAIT {
            get {
                return ResourceManager.GetString("PREPARING_RFID_SCANNER_WAIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Press Button to Modify Box.
        /// </summary>
        internal static string PRESS_BUTTON_MODIFY_BOX {
            get {
                return ResourceManager.GetString("PRESS_BUTTON_MODIFY_BOX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Press Button To Modify User Information.
        /// </summary>
        internal static string PRESS_MODIFY_USER {
            get {
                return ResourceManager.GetString("PRESS_MODIFY_USER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///PROCESSING ID...
        ///
        ///Please Remove ID Now.
        /// </summary>
        internal static string PROCESSING_ID {
            get {
                return ResourceManager.GetString("PROCESSING_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error While Processing ID.
        /// </summary>
        internal static string PROCESSING_ID_ERROR {
            get {
                return ResourceManager.GetString("PROCESSING_ID_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Read Count.
        /// </summary>
        internal static string READ_COUNT {
            get {
                return ResourceManager.GetString("READ_COUNT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inspect And Report Car
        ///Damage On Form Prior
        ///To Leaving.
        /// </summary>
        internal static string REPORT_CAR_DAMAGE {
            get {
                return ResourceManager.GetString("REPORT_CAR_DAMAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reservation Confirmation Timed Out.
        /// </summary>
        internal static string RESERVATION_CONFIRMATION_TIMEOUT {
            get {
                return ResourceManager.GetString("RESERVATION_CONFIRMATION_TIMEOUT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reservation Not Found
        ///Try Again or Please Call
        ///Administrator.
        /// </summary>
        internal static string RESERVATION_NOT_FOUND {
            get {
                return ResourceManager.GetString("RESERVATION_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unfortunately we have
        ///been unable to verify
        /// your reservation
        ///Please call administrator.
        /// </summary>
        internal static string RESERVATION_VERIFICATION_ERROR {
            get {
                return ResourceManager.GetString("RESERVATION_VERIFICATION_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Return.
        /// </summary>
        internal static string RETURN {
            get {
                return ResourceManager.GetString("RETURN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Return Key And Close
        ///Door Firmly When Done..
        /// </summary>
        internal static string RETURN_KEY_CLOSE_DOOR {
            get {
                return ResourceManager.GetString("RETURN_KEY_CLOSE_DOOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RFID Data Error.
        /// </summary>
        internal static string RFID_DATA_ERROR {
            get {
                return ResourceManager.GetString("RFID_DATA_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display RFID Info.
        /// </summary>
        internal static string RFID_INFO_DISPLAY {
            get {
                return ResourceManager.GetString("RFID_INFO_DISPLAY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New RFID
        ///number cancelled.
        /// </summary>
        internal static string RFID_NUMBER_CANCELLED {
            get {
                return ResourceManager.GetString("RFID_NUMBER_CANCELLED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RFID Scan.
        /// </summary>
        internal static string RFID_SCAN {
            get {
                return ResourceManager.GetString("RFID_SCAN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RFID Tag.
        /// </summary>
        internal static string RFID_TAG {
            get {
                return ResourceManager.GetString("RFID_TAG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RFID Tag Found.
        /// </summary>
        internal static string RFID_TAG_FOUND {
            get {
                return ResourceManager.GetString("RFID_TAG_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RFID Tag Not Detected.
        /// </summary>
        internal static string RFID_TAG_NOT_DETECTED {
            get {
                return ResourceManager.GetString("RFID_TAG_NOT_DETECTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No RFID Tag Found
        ///For Box .
        /// </summary>
        internal static string RFID_TAG_NOT_FOUND {
            get {
                return ResourceManager.GetString("RFID_TAG_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string SAVE {
            get {
                return ResourceManager.GetString("SAVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saving Fingerprint
        ///Data.
        /// </summary>
        internal static string SAVING_FINGERPRINTS {
            get {
                return ResourceManager.GetString("SAVING_FINGERPRINTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scan.
        /// </summary>
        internal static string SCAN {
            get {
                return ResourceManager.GetString("SCAN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scan Attempts:.
        /// </summary>
        internal static string SCAN_ATTEMPTS {
            get {
                return ResourceManager.GetString("SCAN_ATTEMPTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scan An Enrolled
        ///Finger On The
        ///Biometric Scanner.
        /// </summary>
        internal static string SCAN_ENROLLED_FINGERPRINT {
            get {
                return ResourceManager.GetString("SCAN_ENROLLED_FINGERPRINT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Press Scan to Begin
        ///Fingerprint .
        /// </summary>
        internal static string SCAN_FINGERPRINT {
            get {
                return ResourceManager.GetString("SCAN_FINGERPRINT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scan HID Card Now.
        /// </summary>
        internal static string SCAN_HID_CARD {
            get {
                return ResourceManager.GetString("SCAN_HID_CARD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number Of
        ///Seconds
        ///To Scan.
        /// </summary>
        internal static string SCAN_LENGTH {
            get {
                return ResourceManager.GetString("SCAN_LENGTH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Must scan for at least
        ///one second.
        /// </summary>
        internal static string SCAN_LENGTH_ERROR {
            get {
                return ResourceManager.GetString("SCAN_LENGTH_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///Place your license on the scanner, photo facing in, front of license against the glass..
        /// </summary>
        internal static string SCAN_LICENSE_FACING_IN {
            get {
                return ResourceManager.GetString("SCAN_LICENSE_FACING_IN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///Place your license on the scanner, photo facing out, back of license against the glass..
        /// </summary>
        internal static string SCAN_LICENSE_FACING_OUT {
            get {
                return ResourceManager.GetString("SCAN_LICENSE_FACING_OUT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scan #.
        /// </summary>
        internal static string SCAN_NUMBER {
            get {
                return ResourceManager.GetString("SCAN_NUMBER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scan Timed Out.
        /// </summary>
        internal static string SCAN_TIMED_OUT {
            get {
                return ResourceManager.GetString("SCAN_TIMED_OUT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scanning....
        /// </summary>
        internal static string SCANNING {
            get {
                return ResourceManager.GetString("SCANNING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scanning for RFID Tag....
        /// </summary>
        internal static string SCANNING_FOR_RFID_TAG {
            get {
                return ResourceManager.GetString("SCANNING_FOR_RFID_TAG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error While Scanning ID:
        ///Transaction Cancelled.
        /// </summary>
        internal static string SCANNING_ID_ERROR {
            get {
                return ResourceManager.GetString("SCANNING_ID_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///
        ///SCANNING ID
        ///
        ///PLEASE WAIT....
        /// </summary>
        internal static string SCANNING_WAIT {
            get {
                return ResourceManager.GetString("SCANNING_WAIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Access Method.
        /// </summary>
        internal static string SELECT_ACCESS_METHOD {
            get {
                return ResourceManager.GetString("SELECT_ACCESS_METHOD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Date.
        /// </summary>
        internal static string SELECT_DATE {
            get {
                return ResourceManager.GetString("SELECT_DATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sending Email
        ///Receipt.
        /// </summary>
        internal static string SENDING_EMAIL_RECEIPT {
            get {
                return ResourceManager.GetString("SENDING_EMAIL_RECEIPT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sending Transaction
        ///History Report.
        /// </summary>
        internal static string SENDING_TRANSACTION_HISTORY {
            get {
                return ResourceManager.GetString("SENDING_TRANSACTION_HISTORY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sending Text
        ///Message Receipt.
        /// </summary>
        internal static string SENDING_TXTMSG_RECEIPT {
            get {
                return ResourceManager.GetString("SENDING_TXTMSG_RECEIPT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service Manager Phone Number.
        /// </summary>
        internal static string SERVICE_MGR_PHONE_NUMBER {
            get {
                return ResourceManager.GetString("SERVICE_MGR_PHONE_NUMBER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set Access Restrictions for Box Number .
        /// </summary>
        internal static string SET_BOX_NUMBER_ACCESS_RESTRICTIONS {
            get {
                return ResourceManager.GetString("SET_BOX_NUMBER_ACCESS_RESTRICTIONS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set End Time.
        /// </summary>
        internal static string SET_END_TIME {
            get {
                return ResourceManager.GetString("SET_END_TIME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set Limited Uses.
        /// </summary>
        internal static string SET_LIMITED_USES {
            get {
                return ResourceManager.GetString("SET_LIMITED_USES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set Start Time.
        /// </summary>
        internal static string SET_START_TIME {
            get {
                return ResourceManager.GetString("SET_START_TIME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set Access Restrictions for User Number .
        /// </summary>
        internal static string SET_USER_ACCESS_RESTRICTIONS {
            get {
                return ResourceManager.GetString("SET_USER_ACCESS_RESTRICTIONS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starting Box Number
        ///Is Greater Than Ending
        ///Box Number.
        /// </summary>
        internal static string START_BOX_GREATER_END_BOX {
            get {
                return ResourceManager.GetString("START_BOX_GREATER_END_BOX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start date is later
        ///than end date.
        /// </summary>
        internal static string START_DATE_LATER {
            get {
                return ResourceManager.GetString("START_DATE_LATER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starting Door Number.
        /// </summary>
        internal static string START_DOOR_NUMBER {
            get {
                return ResourceManager.GetString("START_DOOR_NUMBER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Time.
        /// </summary>
        internal static string START_TIME {
            get {
                return ResourceManager.GetString("START_TIME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Swipe Card.
        /// </summary>
        internal static string SWIPE_CARD {
            get {
                return ResourceManager.GetString("SWIPE_CARD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tag ID.
        /// </summary>
        internal static string TAG_ID {
            get {
                return ResourceManager.GetString("TAG_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Take.
        /// </summary>
        internal static string TAKE {
            get {
                return ResourceManager.GetString("TAKE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Take Key And Close
        ///Door Firmly When Done..
        /// </summary>
        internal static string TAKE_KEY_CLOSE_DOOR {
            get {
                return ResourceManager.GetString("TAKE_KEY_CLOSE_DOOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text Failed.
        ///Local Copy Stored.
        ///Contact Admin.
        ///Thank You.
        /// </summary>
        internal static string TEXT_FAILED {
            get {
                return ResourceManager.GetString("TEXT_FAILED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User text receipt
        ///cancelled.
        /// </summary>
        internal static string TEXT_MESSAGE_CANCELLED {
            get {
                return ResourceManager.GetString("TEXT_MESSAGE_CANCELLED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User text receipt
        ///timed out.
        /// </summary>
        internal static string TEXT_MESSAGE_TIMEOUT {
            get {
                return ResourceManager.GetString("TEXT_MESSAGE_TIMEOUT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text Successful
        ///
        ///Thank You..
        /// </summary>
        internal static string TEXT_SUCCESSFUL {
            get {
                return ResourceManager.GetString("TEXT_SUCCESSFUL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time Period.
        /// </summary>
        internal static string TIME_PERIOD {
            get {
                return ResourceManager.GetString("TIME_PERIOD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time &amp; Limited Uses.
        /// </summary>
        internal static string TIME_PERIOD_LIMITED_USES {
            get {
                return ResourceManager.GetString("TIME_PERIOD_LIMITED_USES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transaction Cancelled.
        /// </summary>
        internal static string TRANSACTION_CANCELLED {
            get {
                return ResourceManager.GetString("TRANSACTION_CANCELLED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display Transactions.
        /// </summary>
        internal static string TRANSACTION_DISPLAY {
            get {
                return ResourceManager.GetString("TRANSACTION_DISPLAY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to transaction files copied.
        /// </summary>
        internal static string TRANSACTIONS_COPIED {
            get {
                return ResourceManager.GetString("TRANSACTIONS_COPIED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to transaction file
        ///copy error.
        /// </summary>
        internal static string TRANSACTIONS_COPY_ERROR {
            get {
                return ResourceManager.GetString("TRANSACTIONS_COPY_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to USB memory stick
        ///not detected.
        /// </summary>
        internal static string USB_NOT_DETECTED {
            get {
                return ResourceManager.GetString("USB_NOT_DETECTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to USB Data Import.
        /// </summary>
        internal static string USB_TRANS_IMPORT {
            get {
                return ResourceManager.GetString("USB_TRANS_IMPORT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use\&quot;Change Admin Password\&quot;
        ///Try Again.
        /// </summary>
        internal static string USE_CHANGE_ADMIN_PWORD {
            get {
                return ResourceManager.GetString("USE_CHANGE_ADMIN_PWORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User.
        /// </summary>
        internal static string USER {
            get {
                return ResourceManager.GetString("USER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User added.
        /// </summary>
        internal static string USER_ADDED {
            get {
                return ResourceManager.GetString("USER_ADDED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User ID.
        /// </summary>
        internal static string USER_ID {
            get {
                return ResourceManager.GetString("USER_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Management.
        /// </summary>
        internal static string USER_MANAGEMENT {
            get {
                return ResourceManager.GetString("USER_MANAGEMENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Does Not Exist.
        /// </summary>
        internal static string USER_NOT_EXIST {
            get {
                return ResourceManager.GetString("USER_NOT_EXIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Type.
        /// </summary>
        internal static string USER_TYPE {
            get {
                return ResourceManager.GetString("USER_TYPE", resourceCulture);
            }
        }
    }
}
