//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KeyCabinetKiosk {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Language_CH {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Language_CH() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("KeyCabinetKiosk.Language_CH", typeof(Language_CH).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 访问.
        /// </summary>
        internal static string ACCESS {
            get {
                return ResourceManager.GetString("ACCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 访问代码与信用/通行卡.
        /// </summary>
        internal static string ACCESS_AND_CARD {
            get {
                return ResourceManager.GetString("ACCESS_AND_CARD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 访问代码.
        /// </summary>
        internal static string ACCESS_CODE {
            get {
                return ResourceManager.GetString("ACCESS_CODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 无用户分配给
        ///此访问代码.
        /// </summary>
        internal static string ACCESS_CODE_NO_USER {
            get {
                return ResourceManager.GetString("ACCESS_CODE_NO_USER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 未找到访问代码.
        /// </summary>
        internal static string ACCESS_CODE_NOT_FOUND {
            get {
                return ResourceManager.GetString("ACCESS_CODE_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 仅限访问代码.
        /// </summary>
        internal static string ACCESS_CODE_ONLY {
            get {
                return ResourceManager.GetString("ACCESS_CODE_ONLY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 访问方式.
        /// </summary>
        internal static string ACCESS_METHOD {
            get {
                return ResourceManager.GetString("ACCESS_METHOD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 访问限制类型.
        /// </summary>
        internal static string ACCESS_RESTRICTION_TYPE {
            get {
                return ResourceManager.GetString("ACCESS_RESTRICTION_TYPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 访问限制.
        /// </summary>
        internal static string ACCESS_RESTRICTIONS {
            get {
                return ResourceManager.GetString("ACCESS_RESTRICTIONS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 添加其它用户.
        /// </summary>
        internal static string ADD_ANOTHER_USER {
            get {
                return ResourceManager.GetString("ADD_ANOTHER_USER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 添加用户.
        /// </summary>
        internal static string ADD_USER {
            get {
                return ResourceManager.GetString("ADD_USER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 更改管理员邮箱.
        /// </summary>
        internal static string ADMIN_EMAIL_ADDRESS {
            get {
                return ResourceManager.GetString("ADMIN_EMAIL_ADDRESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 管理员密码.
        /// </summary>
        internal static string ADMIN_PASSWORD {
            get {
                return ResourceManager.GetString("ADMIN_PASSWORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 服务经理号码.
        /// </summary>
        internal static string ADMIN_PHONE_NUMBER {
            get {
                return ResourceManager.GetString("ADMIN_PHONE_NUMBER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 管理任务.
        /// </summary>
        internal static string ADMIN_TASKS {
            get {
                return ResourceManager.GetString("ADMIN_TASKS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 更改管理员短信号.
        /// </summary>
        internal static string ADMIN_TEXT_NUMBER {
            get {
                return ResourceManager.GetString("ADMIN_TEXT_NUMBER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 请再次扫描同一手
        ///指供登记扫描  计数.
        /// </summary>
        internal static string AGAIN_SCAN_FINGERPRINT {
            get {
                return ResourceManager.GetString("AGAIN_SCAN_FINGERPRINT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 时刻在线.
        /// </summary>
        internal static string ALWAYS_ON {
            get {
                return ResourceManager.GetString("ALWAYS_ON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 应用更改.
        /// </summary>
        internal static string APPLY_CHANGES {
            get {
                return ResourceManager.GetString("APPLY_CHANGES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 你想要.
        /// </summary>
        internal static string ASK_TEXT_MESSAGE_1 {
            get {
                return ResourceManager.GetString("ASK_TEXT_MESSAGE_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 获得文本收据？.
        /// </summary>
        internal static string ASK_TEXT_MESSAGE_2 {
            get {
                return ResourceManager.GetString("ASK_TEXT_MESSAGE_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 后退.
        /// </summary>
        internal static string BACKSPACE {
            get {
                return ResourceManager.GetString("BACKSPACE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 条形码扫描错误：
        ///没有扫描到条形码.
        /// </summary>
        internal static string BARCODE_SCANNING_ERROR {
            get {
                return ResourceManager.GetString("BARCODE_SCANNING_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 电动车.
        /// </summary>
        internal static string BIKE {
            get {
                return ResourceManager.GetString("BIKE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 请选择一个电动
        ///车类型.
        /// </summary>
        internal static string BIKE_CHOOSE {
            get {
                return ResourceManager.GetString("BIKE_CHOOSE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 生物识别登记.
        /// </summary>
        internal static string BIOMETRIC_ENROLLMENT {
            get {
                return ResourceManager.GetString("BIOMETRIC_ENROLLMENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 设置箱子访问权限.
        /// </summary>
        internal static string BOX_ACCESS {
            get {
                return ResourceManager.GetString("BOX_ACCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 察看箱子信息.
        /// </summary>
        internal static string BOX_INFO {
            get {
                return ResourceManager.GetString("BOX_INFO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 钥匙箱位置未设置.
        /// </summary>
        internal static string BOX_LOCATION_NOT_SET {
            get {
                return ResourceManager.GetString("BOX_LOCATION_NOT_SET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 钥匙箱号码.
        /// </summary>
        internal static string BOX_NUMBER {
            get {
                return ResourceManager.GetString("BOX_NUMBER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 钥匙箱号码不存在.
        /// </summary>
        internal static string BOX_NUMBER_NOT_EXIST {
            get {
                return ResourceManager.GetString("BOX_NUMBER_NOT_EXIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 点击开始.
        /// </summary>
        internal static string BUTTON_START {
            get {
                return ResourceManager.GetString("BUTTON_START", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 访问钥匙柜.
        /// </summary>
        internal static string CABINET_BOX_ACCESS {
            get {
                return ResourceManager.GetString("CABINET_BOX_ACCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 柜门状态反馈.
        /// </summary>
        internal static string CABINET_DOOR_TRANSACTIONS {
            get {
                return ResourceManager.GetString("CABINET_DOOR_TRANSACTIONS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 取消.
        /// </summary>
        internal static string CANCEL {
            get {
                return ResourceManager.GetString("CANCEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 已取消.
        /// </summary>
        internal static string CANCELLED {
            get {
                return ResourceManager.GetString("CANCELLED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 大写锁定.
        /// </summary>
        internal static string CAPITALS_LOCK {
            get {
                return ResourceManager.GetString("CAPITALS_LOCK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 信用卡或通行卡号.
        /// </summary>
        internal static string CARD_NUMBER {
            get {
                return ResourceManager.GetString("CARD_NUMBER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 读卡被取消 请重试.
        /// </summary>
        internal static string CARD_READ_CANCELLED {
            get {
                return ResourceManager.GetString("CARD_READ_CANCELLED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 无法识别卡片 请重试.
        /// </summary>
        internal static string CARD_READ_FAILED {
            get {
                return ResourceManager.GetString("CARD_READ_FAILED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 超时 请重试.
        /// </summary>
        internal static string CARD_READ_TIMEOUT {
            get {
                return ResourceManager.GetString("CARD_READ_TIMEOUT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 扫描出错：请重试.
        /// </summary>
        internal static string CARD_SWIPE_ERROR {
            get {
                return ResourceManager.GetString("CARD_SWIPE_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 更改管理员密码.
        /// </summary>
        internal static string CHANGE_ADMIN_PWORD {
            get {
                return ResourceManager.GetString("CHANGE_ADMIN_PWORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 更改密码.
        /// </summary>
        internal static string CHANGE_PASSWORD {
            get {
                return ResourceManager.GetString("CHANGE_PASSWORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 选择导入.csv 或 .xml 文件.
        /// </summary>
        internal static string CHOOSE_IMPORT_FILE {
            get {
                return ResourceManager.GetString("CHOOSE_IMPORT_FILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 清除已登记指纹记录.
        /// </summary>
        internal static string CLEAR_ENROLLED_FINGERPRINTS {
            get {
                return ResourceManager.GetString("CLEAR_ENROLLED_FINGERPRINTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 指纹与其它ID匹配. 清除
        ///之前指纹？.
        /// </summary>
        internal static string CLEAR_FINGERPRINT_QUESTION {
            get {
                return ResourceManager.GetString("CLEAR_FINGERPRINT_QUESTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 清空数据.
        /// </summary>
        internal static string CLEAR_SCAN_TABLE {
            get {
                return ResourceManager.GetString("CLEAR_SCAN_TABLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 正在连接服务器.
        /// </summary>
        internal static string COMMUNICATING_WITH_SERVER {
            get {
                return ResourceManager.GetString("COMMUNICATING_WITH_SERVER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 运行程序出错.
        /// </summary>
        internal static string CONFIGURATION_APP_ERROR {
            get {
                return ResourceManager.GetString("CONFIGURATION_APP_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 配置文件有不可恢
        ///复错误.
        /// </summary>
        internal static string CONFIGURATION_FILE_ERROR {
            get {
                return ResourceManager.GetString("CONFIGURATION_FILE_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 开放接口出现不可
        ///恢复错误.
        /// </summary>
        internal static string CONFIGURATION_OPEN_PORT_ERROR {
            get {
                return ResourceManager.GetString("CONFIGURATION_OPEN_PORT_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 配置文件RFID错误.
        /// </summary>
        internal static string CONFIGURATION_RFID_ERROR_1 {
            get {
                return ResourceManager.GetString("CONFIGURATION_RFID_ERROR_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 警告：若不退出将出
        ///现其它程序错误。
        ///是否继续？.
        /// </summary>
        internal static string CONFIGURATION_RFID_ERROR_2 {
            get {
                return ResourceManager.GetString("CONFIGURATION_RFID_ERROR_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 确认.
        /// </summary>
        internal static string CONFIRM {
            get {
                return ResourceManager.GetString("CONFIRM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 车牌号是否正确？.
        /// </summary>
        internal static string CONFIRM_LICENSE {
            get {
                return ResourceManager.GetString("CONFIRM_LICENSE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 姓名是否正确？.
        /// </summary>
        internal static string CONFIRM_NAME {
            get {
                return ResourceManager.GetString("CONFIRM_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 继续.
        /// </summary>
        internal static string CONTINUE {
            get {
                return ResourceManager.GetString("CONTINUE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 仅限信用卡.
        /// </summary>
        internal static string CREDIT_CARD_ONLY {
            get {
                return ResourceManager.GetString("CREDIT_CARD_ONLY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 当前访问：.
        /// </summary>
        internal static string CURRENT_ACCESS {
            get {
                return ResourceManager.GetString("CURRENT_ACCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 数据文件出错或不存在.
        /// </summary>
        internal static string DATA_FILE_ERRORS_NOT_EXIST {
            get {
                return ResourceManager.GetString("DATA_FILE_ERRORS_NOT_EXIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 数据文件出错.
        /// </summary>
        internal static string DATA_FILE_HAS_ERRORS {
            get {
                return ResourceManager.GetString("DATA_FILE_HAS_ERRORS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 数据文件不存在.
        /// </summary>
        internal static string DATA_FILE_NOT_EXIST {
            get {
                return ResourceManager.GetString("DATA_FILE_NOT_EXIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 信息长度须在.
        /// </summary>
        internal static string DATA_LENGTH_ERROR {
            get {
                return ResourceManager.GetString("DATA_LENGTH_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 字符以内.
        /// </summary>
        internal static string DATA_LENGTH_ERROR_2 {
            get {
                return ResourceManager.GetString("DATA_LENGTH_ERROR_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 程序更新线程出错.
        /// </summary>
        internal static string DATA_UPDATE_ERROR {
            get {
                return ResourceManager.GetString("DATA_UPDATE_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 程序显示线程出错.
        /// </summary>
        internal static string DATA_VIEW_THREAD_ERROR {
            get {
                return ResourceManager.GetString("DATA_VIEW_THREAD_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 数据库出错. 请重试或
        ///拨打服务电话.
        /// </summary>
        internal static string DATABASE_ERROR {
            get {
                return ResourceManager.GetString("DATABASE_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 删除用户.
        /// </summary>
        internal static string DELETE_USER {
            get {
                return ResourceManager.GetString("DELETE_USER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 部门.
        /// </summary>
        internal static string DEPARTMENT {
            get {
                return ResourceManager.GetString("DEPARTMENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 钥匙箱预设操作时间
        ///未到. 取消开门..
        /// </summary>
        internal static string DOOR_TIMEFRAME_BOX_ERROR {
            get {
                return ResourceManager.GetString("DOOR_TIMEFRAME_BOX_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 钥匙箱预设操作时间
        ///已过. 取消开门..
        /// </summary>
        internal static string DOOR_TIMEFRAME_BOX_ERROR_2 {
            get {
                return ResourceManager.GetString("DOOR_TIMEFRAME_BOX_ERROR_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 预设的用户操作时间
        ///未到.取消开门..
        /// </summary>
        internal static string DOOR_TIMEFRAME_USER_ERROR {
            get {
                return ResourceManager.GetString("DOOR_TIMEFRAME_USER_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 预设的用户操作时间
        ///已过.取消开门..
        /// </summary>
        internal static string DOOR_TIMEFRAME_USER_ERROR_2 {
            get {
                return ResourceManager.GetString("DOOR_TIMEFRAME_USER_ERROR_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 此箱子无法再次使用. 
        ///取消开门..
        /// </summary>
        internal static string DOOR_USAGES_BOX_ERROR {
            get {
                return ResourceManager.GetString("DOOR_USAGES_BOX_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 此用户预设使用次数
        ///已到.取消开门..
        /// </summary>
        internal static string DOOR_USAGES_USER_ERROR {
            get {
                return ResourceManager.GetString("DOOR_USAGES_USER_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 输入驾驶者名字
        ///（不含姓氏）.
        /// </summary>
        internal static string DRIVER_FIRST_NAME {
            get {
                return ResourceManager.GetString("DRIVER_FIRST_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 输入驾驶者姓氏.
        /// </summary>
        internal static string DRIVER_LAST_NAME {
            get {
                return ResourceManager.GetString("DRIVER_LAST_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 输入驾照号码.
        /// </summary>
        internal static string DRIVER_NUMBER {
            get {
                return ResourceManager.GetString("DRIVER_NUMBER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 电动自行车.
        /// </summary>
        internal static string EBIKE {
            get {
                return ResourceManager.GetString("EBIKE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 电子邮箱.
        /// </summary>
        internal static string EMAIL {
            get {
                return ResourceManager.GetString("EMAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 电子邮箱地址.
        /// </summary>
        internal static string EMAIL_ADDRESS {
            get {
                return ResourceManager.GetString("EMAIL_ADDRESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 电子邮箱地址格式错误.
        /// </summary>
        internal static string EMAIL_ADDRESS_NOT_FORMATTED {
            get {
                return ResourceManager.GetString("EMAIL_ADDRESS_NOT_FORMATTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 邮件发送失败.，
        ///已存储至本地，
        ///请联系管理员。谢谢！.
        /// </summary>
        internal static string EMAIL_FAILED {
            get {
                return ResourceManager.GetString("EMAIL_FAILED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 邮件发送成功. 谢谢.
        /// </summary>
        internal static string EMAIL_SUCCESSFUL {
            get {
                return ResourceManager.GetString("EMAIL_SUCCESSFUL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to USB交易数据导出.
        /// </summary>
        internal static string EMAIL_TRANSACTION_REPORT {
            get {
                return ResourceManager.GetString("EMAIL_TRANSACTION_REPORT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string EMAIL_TRANSACTIONS_FAILED {
            get {
                return ResourceManager.GetString("EMAIL_TRANSACTIONS_FAILED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string EMAIL_TRANSACTIONS_SUCCESSFUL {
            get {
                return ResourceManager.GetString("EMAIL_TRANSACTIONS_SUCCESSFUL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 开启多个钥匙箱，最
        ///后打开的钥匙箱编号.
        /// </summary>
        internal static string END_DOOR_NUMBER {
            get {
                return ResourceManager.GetString("END_DOOR_NUMBER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 订单完成时间.
        /// </summary>
        internal static string END_TIME {
            get {
                return ResourceManager.GetString("END_TIME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 录入新指纹.
        /// </summary>
        internal static string ENROLL_FINGERPRINTS {
            get {
                return ResourceManager.GetString("ENROLL_FINGERPRINTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 用户已录入指纹数.
        /// </summary>
        internal static string ENROLLED_FINGERPRINT_COUNT {
            get {
                return ResourceManager.GetString("ENROLLED_FINGERPRINT_COUNT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 进入.
        /// </summary>
        internal static string ENTER {
            get {
                return ResourceManager.GetString("ENTER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 输入访问代码.
        /// </summary>
        internal static string ENTER_ACCESS_CODE {
            get {
                return ResourceManager.GetString("ENTER_ACCESS_CODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 输入箱子号.
        /// </summary>
        internal static string ENTER_BOX_NUMBER {
            get {
                return ResourceManager.GetString("ENTER_BOX_NUMBER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 输入卡号.
        /// </summary>
        internal static string ENTER_CARD_NUMBER {
            get {
                return ResourceManager.GetString("ENTER_CARD_NUMBER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 输入需要更改的钥匙
        ///箱访问码.
        /// </summary>
        internal static string ENTER_CODE {
            get {
                return ResourceManager.GetString("ENTER_CODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 输入部门名称.
        /// </summary>
        internal static string ENTER_DEPARTMENT_NAME {
            get {
                return ResourceManager.GetString("ENTER_DEPARTMENT_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 开启多个钥匙箱 - 输入
        ///各钥匙箱开启间隔时间.
        /// </summary>
        internal static string ENTER_DOOR_DELAY {
            get {
                return ResourceManager.GetString("ENTER_DOOR_DELAY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 输入电子邮箱地址.
        /// </summary>
        internal static string ENTER_EMAIL_ADDRESS {
            get {
                return ResourceManager.GetString("ENTER_EMAIL_ADDRESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 开启多个钥匙箱，最
        ///后打开的钥匙箱编号.
        /// </summary>
        internal static string ENTER_END_DOOR {
            get {
                return ResourceManager.GetString("ENTER_END_DOOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 输入结束时间.
        /// </summary>
        internal static string ENTER_END_TIME {
            get {
                return ResourceManager.GetString("ENTER_END_TIME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 输入名字（不含姓氏）.
        /// </summary>
        internal static string ENTER_FIRST_NAME {
            get {
                return ResourceManager.GetString("ENTER_FIRST_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 输入群组名称.
        /// </summary>
        internal static string ENTER_GROUP_NAME {
            get {
                return ResourceManager.GetString("ENTER_GROUP_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 输入ID.
        /// </summary>
        internal static string ENTER_ID {
            get {
                return ResourceManager.GetString("ENTER_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 输入姓氏.
        /// </summary>
        internal static string ENTER_LAST_NAME {
            get {
                return ResourceManager.GetString("ENTER_LAST_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 输入驾照号.
        /// </summary>
        internal static string ENTER_LICENSE_NUMBER {
            get {
                return ResourceManager.GetString("ENTER_LICENSE_NUMBER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 进入开启次数限制.
        /// </summary>
        internal static string ENTER_LIMITED_USES {
            get {
                return ResourceManager.GetString("ENTER_LIMITED_USES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 输入新代码.
        /// </summary>
        internal static string ENTER_NEW_CODE {
            get {
                return ResourceManager.GetString("ENTER_NEW_CODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 输入新ID.
        /// </summary>
        internal static string ENTER_NEW_ID {
            get {
                return ResourceManager.GetString("ENTER_NEW_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 输入汽车里程表读数.
        /// </summary>
        internal static string ENTER_ODOMETER_READING {
            get {
                return ResourceManager.GetString("ENTER_ODOMETER_READING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 输入操作员编号.
        /// </summary>
        internal static string ENTER_OPERATOR_NUMBER {
            get {
                return ResourceManager.GetString("ENTER_OPERATOR_NUMBER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 输入电话号码.
        /// </summary>
        internal static string ENTER_PHONE_NUMBER {
            get {
                return ResourceManager.GetString("ENTER_PHONE_NUMBER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 输入RFID标签号.
        /// </summary>
        internal static string ENTER_RFID_TAG {
            get {
                return ResourceManager.GetString("ENTER_RFID_TAG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 开启多个钥匙箱，首
        ///先打开的钥匙箱编号.
        /// </summary>
        internal static string ENTER_START_DOOR {
            get {
                return ResourceManager.GetString("ENTER_START_DOOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 输入开始时间.
        /// </summary>
        internal static string ENTER_START_TIME {
            get {
                return ResourceManager.GetString("ENTER_START_TIME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 输入用户ID.
        /// </summary>
        internal static string ENTER_USER_ID {
            get {
                return ResourceManager.GetString("ENTER_USER_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 输入要删除的用户ID.
        /// </summary>
        internal static string ENTER_USER_ID_DELETE {
            get {
                return ResourceManager.GetString("ENTER_USER_ID_DELETE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 输入要修改的用户ID.
        /// </summary>
        internal static string ENTER_USER_ID_MODIFY {
            get {
                return ResourceManager.GetString("ENTER_USER_ID_MODIFY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 输入车辆号.
        /// </summary>
        internal static string ENTER_VEHICLE_NUMBER {
            get {
                return ResourceManager.GetString("ENTER_VEHICLE_NUMBER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 退出.
        /// </summary>
        internal static string EXIT {
            get {
                return ResourceManager.GetString("EXIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 每辆车都配有一个含
        ///有车辆分配里程日志
        ///的黄色文件夹。司机
        ///在每个驾驶日都须填
        ///写完整。.
        /// </summary>
        internal static string FILL_OUT_MILEAGE_FORM {
            get {
                return ResourceManager.GetString("FILL_OUT_MILEAGE_FORM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 指纹匹配失败.
        /// </summary>
        internal static string FINGERPRINT_FAILED {
            get {
                return ResourceManager.GetString("FINGERPRINT_FAILED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 指纹匹配成功.
        /// </summary>
        internal static string FINGERPRINT_MATCHED {
            get {
                return ResourceManager.GetString("FINGERPRINT_MATCHED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 指纹已清除.
        /// </summary>
        internal static string FINGERPRINTS_CLEARED {
            get {
                return ResourceManager.GetString("FINGERPRINTS_CLEARED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 名字（不含姓氏）.
        /// </summary>
        internal static string FIRST_NAME {
            get {
                return ResourceManager.GetString("FIRST_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 群组.
        /// </summary>
        internal static string GROUP {
            get {
                return ResourceManager.GetString("GROUP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 输入管理
        ///员代码退
        ///出程序.
        /// </summary>
        internal static string HIDDEN_EXIT_KEYPAD_MESSAGE {
            get {
                return ResourceManager.GetString("HIDDEN_EXIT_KEYPAD_MESSAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 输入用户ID做生物
        ///登记.
        /// </summary>
        internal static string ID_BIOMETRIC_ENROLLING {
            get {
                return ResourceManager.GetString("ID_BIOMETRIC_ENROLLING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID号已存在.
        /// </summary>
        internal static string ID_NUM_NOT_UNIQUE {
            get {
                return ResourceManager.GetString("ID_NUM_NOT_UNIQUE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID号.
        /// </summary>
        internal static string ID_NUMBER {
            get {
                return ResourceManager.GetString("ID_NUMBER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID已扫描 请移开证件.
        /// </summary>
        internal static string ID_SCAN_CONFIRMED {
            get {
                return ResourceManager.GetString("ID_SCAN_CONFIRMED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID扫描超时.
        /// </summary>
        internal static string ID_SCAN_TIMED_OUT {
            get {
                return ResourceManager.GetString("ID_SCAN_TIMED_OUT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID扫描设备出错.
        /// </summary>
        internal static string ID_SCANNER_ERROR {
            get {
                return ResourceManager.GetString("ID_SCANNER_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 导入完成 弹出USB设备.
        /// </summary>
        internal static string IMPORT_COMPLETE {
            get {
                return ResourceManager.GetString("IMPORT_COMPLETE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 导入访问代码还是
        ///用户数据？.
        /// </summary>
        internal static string IMPORT_QUESTION {
            get {
                return ResourceManager.GetString("IMPORT_QUESTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 正在导入….
        /// </summary>
        internal static string IMPORTING {
            get {
                return ResourceManager.GetString("IMPORTING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 信息.
        /// </summary>
        internal static string INFORMATION {
            get {
                return ResourceManager.GetString("INFORMATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 插入USB驱动器.
        /// </summary>
        internal static string INSERT_USB_DRIVE {
            get {
                return ResourceManager.GetString("INSERT_USB_DRIVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 无效访问类型.
        /// </summary>
        internal static string INVALID_ACCESS_TYPE {
            get {
                return ResourceManager.GetString("INVALID_ACCESS_TYPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 无效箱子号 请重试.
        /// </summary>
        internal static string INVALID_BOX_NUMBER {
            get {
                return ResourceManager.GetString("INVALID_BOX_NUMBER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 无效地址 请重试.
        /// </summary>
        internal static string INVALID_LOCATION {
            get {
                return ResourceManager.GetString("INVALID_LOCATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 无效密码.
        /// </summary>
        internal static string INVALID_PASSWORD {
            get {
                return ResourceManager.GetString("INVALID_PASSWORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 无效时间或日期.
        /// </summary>
        internal static string INVALID_TIME {
            get {
                return ResourceManager.GetString("INVALID_TIME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 姓氏.
        /// </summary>
        internal static string LAST_NAME {
            get {
                return ResourceManager.GetString("LAST_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 使用次数及时间限制.
        /// </summary>
        internal static string LIMIT_PLUS_TIME_PERIOD {
            get {
                return ResourceManager.GetString("LIMIT_PLUS_TIME_PERIOD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 使用次数限制.
        /// </summary>
        internal static string LIMITED_NUMBER_OF_USES {
            get {
                return ResourceManager.GetString("LIMITED_NUMBER_OF_USES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 使用次数限制.
        /// </summary>
        internal static string LIMITED_USES {
            get {
                return ResourceManager.GetString("LIMITED_USES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 手动输入.
        /// </summary>
        internal static string MANUAL_ENTRY {
            get {
                return ResourceManager.GetString("MANUAL_ENTRY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 取消手动输入ID.
        /// </summary>
        internal static string MANUAL_ID_CANCELLED {
            get {
                return ResourceManager.GetString("MANUAL_ID_CANCELLED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 修改用户设置.
        /// </summary>
        internal static string MODIFY_USER {
            get {
                return ResourceManager.GetString("MODIFY_USER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 指纹与多个用户匹配. 
        ///请重试.
        /// </summary>
        internal static string MULTIPLE_FINGERPRINT_MATCHES {
            get {
                return ResourceManager.GetString("MULTIPLE_FINGERPRINT_MATCHES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 姓名.
        /// </summary>
        internal static string NAME {
            get {
                return ResourceManager.GetString("NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 输入新管理员电子邮箱.
        /// </summary>
        internal static string NEW_ADMIN_EMAIL {
            get {
                return ResourceManager.GetString("NEW_ADMIN_EMAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 输入管理员手机号.
        /// </summary>
        internal static string NEW_ADMIN_TXT_NUMBER {
            get {
                return ResourceManager.GetString("NEW_ADMIN_TXT_NUMBER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 新访问码输入被取消.
        /// </summary>
        internal static string NEW_NUMBER_CANCELLED {
            get {
                return ResourceManager.GetString("NEW_NUMBER_CANCELLED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 新管理员密码输入被
        ///取消.
        /// </summary>
        internal static string NEW_PASSWORD_CANCELLED {
            get {
                return ResourceManager.GetString("NEW_PASSWORD_CANCELLED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 请扫描新指纹以登记.
        /// </summary>
        internal static string NEW_SCAN_FINGERPRINT {
            get {
                return ResourceManager.GetString("NEW_SCAN_FINGERPRINT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 不接受空数据.
        /// </summary>
        internal static string NO_EMPTY_DATA {
            get {
                return ResourceManager.GetString("NO_EMPTY_DATA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to N/A.
        /// </summary>
        internal static string NOT_AVAILABLE {
            get {
                return ResourceManager.GetString("NOT_AVAILABLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 大写字母锁定[关].
        /// </summary>
        internal static string OFF {
            get {
                return ResourceManager.GetString("OFF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 确认.
        /// </summary>
        internal static string OK {
            get {
                return ResourceManager.GetString("OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 清除原有指纹.
        /// </summary>
        internal static string OLD_PRINTS_CLEARED {
            get {
                return ResourceManager.GetString("OLD_PRINTS_CLEARED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 开.
        /// </summary>
        internal static string ON {
            get {
                return ResourceManager.GetString("ON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 打开所有门.
        /// </summary>
        internal static string OPEN_ALL_DOORS {
            get {
                return ResourceManager.GetString("OPEN_ALL_DOORS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 打开箱门.
        /// </summary>
        internal static string OPEN_BOX_DOOR {
            get {
                return ResourceManager.GetString("OPEN_BOX_DOOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 开门.
        /// </summary>
        internal static string OPEN_DOOR {
            get {
                return ResourceManager.GetString("OPEN_DOOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 延迟开门.
        /// </summary>
        internal static string OPEN_DOOR_DELAY {
            get {
                return ResourceManager.GetString("OPEN_DOOR_DELAY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 开门.
        /// </summary>
        internal static string OPEN_DOORS {
            get {
                return ResourceManager.GetString("OPEN_DOORS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 钥匙箱开关控制出错误.
        /// </summary>
        internal static string OPEN_RELAY_ERROR {
            get {
                return ResourceManager.GetString("OPEN_RELAY_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 打开箱子.
        /// </summary>
        internal static string OPENING_BOX {
            get {
                return ResourceManager.GetString("OPENING_BOX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 操作超时.
        /// </summary>
        internal static string OPERATION_TIMED_OUT {
            get {
                return ResourceManager.GetString("OPERATION_TIMED_OUT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 其它数据.
        /// </summary>
        internal static string OTHER_DATA {
            get {
                return ResourceManager.GetString("OTHER_DATA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 电动自行车已无货. 
        ///您是否希望租一辆
        ///普通自行车？.
        /// </summary>
        internal static string OUT_OF_STOCK_EBIKE {
            get {
                return ResourceManager.GetString("OUT_OF_STOCK_EBIKE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 普通自行车已无货. 
        ///您是否希望租一辆
        ///电动自行车？.
        /// </summary>
        internal static string OUT_OF_STOCK_NORMAL_BIKE {
            get {
                return ResourceManager.GetString("OUT_OF_STOCK_NORMAL_BIKE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 下一页.
        /// </summary>
        internal static string PAGE_DOWN {
            get {
                return ResourceManager.GetString("PAGE_DOWN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 上一页.
        /// </summary>
        internal static string PAGE_UP {
            get {
                return ResourceManager.GetString("PAGE_UP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 密码长度须在.
        /// </summary>
        internal static string PASSWORD_LENGTH_ERROR {
            get {
                return ResourceManager.GetString("PASSWORD_LENGTH_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 字符以内.
        /// </summary>
        internal static string PASSWORD_LENGTH_ERROR_2 {
            get {
                return ResourceManager.GetString("PASSWORD_LENGTH_ERROR_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 用户电话.
        /// </summary>
        internal static string PHONE {
            get {
                return ResourceManager.GetString("PHONE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 电话号码.
        /// </summary>
        internal static string PHONE_NUMBER {
            get {
                return ResourceManager.GetString("PHONE_NUMBER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 将登记手指放在电
        ///子生物扫描设备上.
        /// </summary>
        internal static string PLACE_ENROLLED_FINGER {
            get {
                return ResourceManager.GetString("PLACE_ENROLLED_FINGER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 正在启用RFID扫描
        ///设备，请稍候….
        /// </summary>
        internal static string PREPARING_RFID_SCANNER_WAIT {
            get {
                return ResourceManager.GetString("PREPARING_RFID_SCANNER_WAIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 修改钥匙箱信息.
        /// </summary>
        internal static string PRESS_BUTTON_MODIFY_BOX {
            get {
                return ResourceManager.GetString("PRESS_BUTTON_MODIFY_BOX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 按下按钮修改用户信息.
        /// </summary>
        internal static string PRESS_MODIFY_USER {
            get {
                return ResourceManager.GetString("PRESS_MODIFY_USER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID处理中…现在
        ///请移开ID.
        /// </summary>
        internal static string PROCESSING_ID {
            get {
                return ResourceManager.GetString("PROCESSING_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 处理ID时出错.
        /// </summary>
        internal static string PROCESSING_ID_ERROR {
            get {
                return ResourceManager.GetString("PROCESSING_ID_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 读数.
        /// </summary>
        internal static string READ_COUNT {
            get {
                return ResourceManager.GetString("READ_COUNT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 离开前检查并在表格
        ///上汇报车辆受损情况.
        /// </summary>
        internal static string REPORT_CAR_DAMAGE {
            get {
                return ResourceManager.GetString("REPORT_CAR_DAMAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 预订确认超时.
        /// </summary>
        internal static string RESERVATION_CONFIRMATION_TIMEOUT {
            get {
                return ResourceManager.GetString("RESERVATION_CONFIRMATION_TIMEOUT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 未找到预订信息.请再
        ///次尝试或联系管理员.
        /// </summary>
        internal static string RESERVATION_NOT_FOUND {
            get {
                return ResourceManager.GetString("RESERVATION_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 我们无法验证您的预
        ///订信息. 请联系管理员.
        /// </summary>
        internal static string RESERVATION_VERIFICATION_ERROR {
            get {
                return ResourceManager.GetString("RESERVATION_VERIFICATION_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 取/还钥匙.
        /// </summary>
        internal static string RETURN {
            get {
                return ResourceManager.GetString("RETURN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 请归还钥匙并关紧箱门.
        /// </summary>
        internal static string RETURN_KEY_CLOSE_DOOR {
            get {
                return ResourceManager.GetString("RETURN_KEY_CLOSE_DOOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RFID数据错误.
        /// </summary>
        internal static string RFID_DATA_ERROR {
            get {
                return ResourceManager.GetString("RFID_DATA_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 显示RFID信息.
        /// </summary>
        internal static string RFID_INFO_DISPLAY {
            get {
                return ResourceManager.GetString("RFID_INFO_DISPLAY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 新RFID号码输入已取消.
        /// </summary>
        internal static string RFID_NUMBER_CANCELLED {
            get {
                return ResourceManager.GetString("RFID_NUMBER_CANCELLED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RFID扫描.
        /// </summary>
        internal static string RFID_SCAN {
            get {
                return ResourceManager.GetString("RFID_SCAN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RFID标签.
        /// </summary>
        internal static string RFID_TAG {
            get {
                return ResourceManager.GetString("RFID_TAG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 找到RFID标签.
        /// </summary>
        internal static string RFID_TAG_FOUND {
            get {
                return ResourceManager.GetString("RFID_TAG_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 未检测到RFID标签.
        /// </summary>
        internal static string RFID_TAG_NOT_DETECTED {
            get {
                return ResourceManager.GetString("RFID_TAG_NOT_DETECTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 未检测到箱子的RFID
        ///标签.
        /// </summary>
        internal static string RFID_TAG_NOT_FOUND {
            get {
                return ResourceManager.GetString("RFID_TAG_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 保存.
        /// </summary>
        internal static string SAVE {
            get {
                return ResourceManager.GetString("SAVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 指纹数据储存中.
        /// </summary>
        internal static string SAVING_FINGERPRINTS {
            get {
                return ResourceManager.GetString("SAVING_FINGERPRINTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 扫描.
        /// </summary>
        internal static string SCAN {
            get {
                return ResourceManager.GetString("SCAN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 尝试扫描.
        /// </summary>
        internal static string SCAN_ATTEMPTS {
            get {
                return ResourceManager.GetString("SCAN_ATTEMPTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 扫描已生物登记过
        ///的指纹.
        /// </summary>
        internal static string SCAN_ENROLLED_FINGERPRINT {
            get {
                return ResourceManager.GetString("SCAN_ENROLLED_FINGERPRINT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 点击“扫描”开始指
        ///纹识别.
        /// </summary>
        internal static string SCAN_FINGERPRINT {
            get {
                return ResourceManager.GetString("SCAN_FINGERPRINT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 扫描HID卡.
        /// </summary>
        internal static string SCAN_HID_CARD {
            get {
                return ResourceManager.GetString("SCAN_HID_CARD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 扫描秒数.
        /// </summary>
        internal static string SCAN_LENGTH {
            get {
                return ResourceManager.GetString("SCAN_LENGTH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 扫描时间需保持最少1秒.
        /// </summary>
        internal static string SCAN_LENGTH_ERROR {
            get {
                return ResourceManager.GetString("SCAN_LENGTH_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 把驾照置于扫描仪上，
        ///照片底部向里，
        ///驾照正面朝玻璃。.
        /// </summary>
        internal static string SCAN_LICENSE_FACING_IN {
            get {
                return ResourceManager.GetString("SCAN_LICENSE_FACING_IN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 把驾照置于扫描仪上，
        ///照片底部向外，
        ///驾照背面朝玻璃。.
        /// </summary>
        internal static string SCAN_LICENSE_FACING_OUT {
            get {
                return ResourceManager.GetString("SCAN_LICENSE_FACING_OUT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RFID标签扫描顺序.
        /// </summary>
        internal static string SCAN_NUMBER {
            get {
                return ResourceManager.GetString("SCAN_NUMBER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 扫描超时 .
        /// </summary>
        internal static string SCAN_TIMED_OUT {
            get {
                return ResourceManager.GetString("SCAN_TIMED_OUT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 扫描中.
        /// </summary>
        internal static string SCANNING {
            get {
                return ResourceManager.GetString("SCANNING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 扫描RFID.
        /// </summary>
        internal static string SCANNING_FOR_RFID_TAG {
            get {
                return ResourceManager.GetString("SCANNING_FOR_RFID_TAG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 扫描ID出错：交易取消.
        /// </summary>
        internal static string SCANNING_ID_ERROR {
            get {
                return ResourceManager.GetString("SCANNING_ID_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 请稍候，正在扫描ID.
        /// </summary>
        internal static string SCANNING_WAIT {
            get {
                return ResourceManager.GetString("SCANNING_WAIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 选择访问方法 .
        /// </summary>
        internal static string SELECT_ACCESS_METHOD {
            get {
                return ResourceManager.GetString("SELECT_ACCESS_METHOD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 选择 日期.
        /// </summary>
        internal static string SELECT_DATE {
            get {
                return ResourceManager.GetString("SELECT_DATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 发送电子邮件确
        ///认函至用户.
        /// </summary>
        internal static string SENDING_EMAIL_RECEIPT {
            get {
                return ResourceManager.GetString("SENDING_EMAIL_RECEIPT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string SENDING_TRANSACTION_HISTORY {
            get {
                return ResourceManager.GetString("SENDING_TRANSACTION_HISTORY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 发送短信确认
        ///函至用户.
        /// </summary>
        internal static string SENDING_TXTMSG_RECEIPT {
            get {
                return ResourceManager.GetString("SENDING_TXTMSG_RECEIPT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 服务经理的电话.
        /// </summary>
        internal static string SERVICE_MGR_PHONE_NUMBER {
            get {
                return ResourceManager.GetString("SERVICE_MGR_PHONE_NUMBER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 为箱号设置访问次数
        ///或时间限制.
        /// </summary>
        internal static string SET_BOX_NUMBER_ACCESS_RESTRICTIONS {
            get {
                return ResourceManager.GetString("SET_BOX_NUMBER_ACCESS_RESTRICTIONS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 设置结束时间.
        /// </summary>
        internal static string SET_END_TIME {
            get {
                return ResourceManager.GetString("SET_END_TIME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 设置使用次数限制.
        /// </summary>
        internal static string SET_LIMITED_USES {
            get {
                return ResourceManager.GetString("SET_LIMITED_USES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 设置开始时间.
        /// </summary>
        internal static string SET_START_TIME {
            get {
                return ResourceManager.GetString("SET_START_TIME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 为用户设置访问时间
        ///或次数限制.
        /// </summary>
        internal static string SET_USER_ACCESS_RESTRICTIONS {
            get {
                return ResourceManager.GetString("SET_USER_ACCESS_RESTRICTIONS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 错误：起始箱号大于
        ///结尾箱号.
        /// </summary>
        internal static string START_BOX_GREATER_END_BOX {
            get {
                return ResourceManager.GetString("START_BOX_GREATER_END_BOX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 错误：起始日期晚于
        ///结束日期.
        /// </summary>
        internal static string START_DATE_LATER {
            get {
                return ResourceManager.GetString("START_DATE_LATER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 起始门号.
        /// </summary>
        internal static string START_DOOR_NUMBER {
            get {
                return ResourceManager.GetString("START_DOOR_NUMBER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 起始时间.
        /// </summary>
        internal static string START_TIME {
            get {
                return ResourceManager.GetString("START_TIME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 刷卡.
        /// </summary>
        internal static string SWIPE_CARD {
            get {
                return ResourceManager.GetString("SWIPE_CARD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 标签ID.
        /// </summary>
        internal static string TAG_ID {
            get {
                return ResourceManager.GetString("TAG_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 领取.
        /// </summary>
        internal static string TAKE {
            get {
                return ResourceManager.GetString("TAKE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 请取走钥匙并关紧柜门.
        /// </summary>
        internal static string TAKE_KEY_CLOSE_DOOR {
            get {
                return ResourceManager.GetString("TAKE_KEY_CLOSE_DOOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 文本发送失败，副本已
        ///保存在本地，请联
        ///系管理员。谢谢.
        /// </summary>
        internal static string TEXT_FAILED {
            get {
                return ResourceManager.GetString("TEXT_FAILED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 用户取消文本接收.
        /// </summary>
        internal static string TEXT_MESSAGE_CANCELLED {
            get {
                return ResourceManager.GetString("TEXT_MESSAGE_CANCELLED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 用户文本接收超时.
        /// </summary>
        internal static string TEXT_MESSAGE_TIMEOUT {
            get {
                return ResourceManager.GetString("TEXT_MESSAGE_TIMEOUT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 文本发送成功.
        /// </summary>
        internal static string TEXT_SUCCESSFUL {
            get {
                return ResourceManager.GetString("TEXT_SUCCESSFUL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 钥匙箱或用户有时
        ///间限制.
        /// </summary>
        internal static string TIME_PERIOD {
            get {
                return ResourceManager.GetString("TIME_PERIOD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 钥匙箱或用户有时
        ///间及使用次数限制.
        /// </summary>
        internal static string TIME_PERIOD_LIMITED_USES {
            get {
                return ResourceManager.GetString("TIME_PERIOD_LIMITED_USES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 信号传输已取消.
        /// </summary>
        internal static string TRANSACTION_CANCELLED {
            get {
                return ResourceManager.GetString("TRANSACTION_CANCELLED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 显示所有最近箱
        ///门开启状态.
        /// </summary>
        internal static string TRANSACTION_DISPLAY {
            get {
                return ResourceManager.GetString("TRANSACTION_DISPLAY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 信号传输信息已复制.
        /// </summary>
        internal static string TRANSACTIONS_COPIED {
            get {
                return ResourceManager.GetString("TRANSACTIONS_COPIED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 信号传输信息复制错误 .
        /// </summary>
        internal static string TRANSACTIONS_COPY_ERROR {
            get {
                return ResourceManager.GetString("TRANSACTIONS_COPY_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 未检测到USB.
        /// </summary>
        internal static string USB_NOT_DETECTED {
            get {
                return ResourceManager.GetString("USB_NOT_DETECTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to USB交易数据导入.
        /// </summary>
        internal static string USB_TRANS_IMPORT {
            get {
                return ResourceManager.GetString("USB_TRANS_IMPORT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 请点击“更改管理员
        ///密码”键重试.
        /// </summary>
        internal static string USE_CHANGE_ADMIN_PWORD {
            get {
                return ResourceManager.GetString("USE_CHANGE_ADMIN_PWORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 用户.
        /// </summary>
        internal static string USER {
            get {
                return ResourceManager.GetString("USER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 用户已添加.
        /// </summary>
        internal static string USER_ADDED {
            get {
                return ResourceManager.GetString("USER_ADDED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 用户ID.
        /// </summary>
        internal static string USER_ID {
            get {
                return ResourceManager.GetString("USER_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 用户管理.
        /// </summary>
        internal static string USER_MANAGEMENT {
            get {
                return ResourceManager.GetString("USER_MANAGEMENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 此用户不存在.
        /// </summary>
        internal static string USER_NOT_EXIST {
            get {
                return ResourceManager.GetString("USER_NOT_EXIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 用户类型.
        /// </summary>
        internal static string USER_TYPE {
            get {
                return ResourceManager.GetString("USER_TYPE", resourceCulture);
            }
        }
    }
}
